include $(APPDIR)/Make.defs

# M+++ built-in application info

PROGNAME  = $(CONFIG_EXAMPLES_M_THREE_PLUS_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_M_THREE_PLUS_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_M_THREE_PLUS_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_M_THREE_PLUS)

# M+++ init file

MAINSRC = server.c

include $(APPDIR)/Application.mk
